theme: jekyll-theme-minimal
title: Hassan Abdallah
logo: /img/Hassan_Abdallah-1.jpg
description: 

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Projects: 
    - Research: "research"
    - Publications: "publications"
 #  Teaching: "teaching"
  CV/About Me: "aboutme"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image
